openapi: 3.0.0
info:
  title: RestCountries API
  version: 1.0.0 ##Major.Minor.bug
servers:
  - url: http://127.0.0.1:8000
    description: Local Server
paths:
  /api/api-token-auth/:
    post:
      summary: Returns token key of user
      description: Perform a post request with valid username and password to get Token key for that user in order to view data.
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                    type: string
                    example: p123p123
      responses:
        "200":
          description: Returns the Token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: d46828fb1f0325bf46b7a6de78880aef5557daa9              

  /api/countries/:
    get:
      security:
        - api_key: []
      summary: Retuns a list of countries.
      description: Retuns a list of countries or queried country. Country can be searched by 'name' keyword in query params.
      parameters:
        - name: name
          in: query
          required: False
          schema:
            type: string
            example: Afghanistan
      responses:
        "200": # status code
          description: Returns a lis of ccountries or queried country.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/countries_schema"

        "401":
          $ref: "#/components/responses/401unauthorized_response"

    post:
      security:
        - api_key: []
      summary: Creates a new country instance.
      description: Takes all values of a country object and creates a new country in database.
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Bangladesh
                alphacode_2:
                  type: string
                  example: BD
                capital:
                  type: string
                  example: Dhaka
                population:
                  type: integer
                  example: 18000000
                timezone:
                  type: string
                  example: UTC+06
                flag:
                  type: string
                  example: https://restcountries.eu/data/bd.svg
      responses:
        "201":
          description: Returns 201 status code if new country is created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 153520e2-8412-4450-9e3e-1cb23d5c1daa
                  name:
                    type: string
                    example: Bangladesh
                  alphacode_2:
                    type: string
                    example: BD
                  capital:
                    type: string
                    example: Dhaka
                  population:
                    type: integer
                    example: 18000000
                  timezone:
                    type: string
                    example: UTC+6
                  flag:
                    type: string
                    example: https://restcountries.eu/data/bd.svg
        "400":
          description: Returns 400 status code if instance with same name and flag already exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  non_field_errors:
                    type: array
                    items:
                      type: string
                      example: "The fields name, flag must make a unique set."
        "401":
          $ref: "#/components/responses/401unauthorized_response"

  /api/countries/{country_id}/:
    get:
      security:
        - api_key: []
      summary: Returns a specific country's detail
      description: Returns all details of a country (the country of country_id ID) including the spoken languages and neighbouring countries name.
      parameters:
        - name: country_id
          in: path
          required: True
          schema:
            type: string
            example: 153520e2-8412-4450-9e3e-1cb23d5c1daa
      responses:
        "200":
          description: Returns 200 status code if country details with country_id is found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 8368ac3c-59ea-408e-b9b3-1351ee7ab397
                  name:
                    type: string
                    example: Afghanistan
                  alphacode_2:
                    type: string
                    example: AF
                  capital:
                    type: string
                    example: Kabul
                  population:
                    type: integer
                    example: 27657145
                  timezone:
                    type: string
                    example: UTC+04:3
                  flag:
                    type: string
                    example: https://restcountries.eu/data/afg.svg
                  languages:
                    type: array
                    items:
                      type: string
                    example: [Turkmen, Uzbek, Pashto]
                  neighbours:
                    type: array
                    items:
                      type: string
                    example:
                      [
                        China,
                        Tajikistan,
                        Uzbekistan,
                        Turkmenistan,
                        Pakistan,
                        Iran (Islamic Republic of),
                      ]
        "401":
          $ref: "#/components/responses/401unauthorized_response"

    put:
      security:
        - api_key: []
      summary: Updates all fields of an existing country.
      description: Takes all new values of an existing country (the country of country_id ID) and updates the instance accordingly. For updating all fields at once, put request should be performed.
      parameters:
        - name: country_id
          in: path
          required: True
          schema:
            type: string
            example: 153520e2-8412-4450-9e3e-1cb23d5c1daa
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Bangladesh (peoples republic)
                alphacode_2:
                  type: string
                  example: BR
                capital:
                  type: string
                  example: chittagong
                population:
                  type: integer
                  example: 18100000
                timezone:
                  type: string
                  example: UTC+7
                flag:
                  type: string
                  example: https://restcountries.eu/data/bdg.svg
      responses:
        "200":
          description: Returns 200 status code if instance is updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 153520e2-8412-4450-9e3e-1cb23d5c1daa
                  name:
                    type: string
                    example: Bangladesh (peoples republic)
                  alphacode_2:
                    type: string
                    example: BR
                  capital:
                    type: string
                    example: chittagong
                  population:
                    type: integer
                    example: 18100000
                  timezone:
                    type: string
                    example: UTC+7
                  flag:
                    type: string
                    example: https://restcountries.eu/data/bdg.svg
        "401":
          $ref: "#/components/responses/401unauthorized_response"

    patch:
      security:
        - api_key: []
      summary: Updates an existing country partially.
      description: Takes one or multiple new values of an existing country (the country of country_id ID) and updates the instance accordingly. For updating only some fields of a country, patch request should be performed.
      parameters:
        - name: country_id
          in: path
          required: True
          schema:
            type: string
            example: 153520e2-8412-4450-9e3e-1cb23d5c1daa
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
              properties:
                capital:
                  type: string
                  example: chittagong
      responses:
        "200":
          description: Returns 200 status code if instance is updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 153520e2-8412-4450-9e3e-1cb23d5c1daa
                  name:
                    type: string
                    example: Bangladesh
                  alphacode_2:
                    type: string
                    example: BD
                  capital:
                    type: string
                    example: chittagong
                  population:
                    type: integer
                    example: 18000000
                  timezone:
                    type: string
                    example: UTC+6
                  flag:
                    type: string
                    example: https://restcountries.eu/data/bd.svg
        "401":
          $ref: "#/components/responses/401unauthorized_response"

    delete:
      security:
        - api_key: []
      summary: Deletes an existing country.
      parameters:
        - name: country_id
          in: path
          required: True
          schema:
            type: string
            example: 153520e2-8412-4450-9e3e-1cb23d5c1daa
      responses:
        "204":
          description: Returns 204 status code if country is deleted.
        "401":
          $ref: "#/components/responses/401unauthorized_response"

  /api/countries/{country_id}/neighbouring-countries/:
    get:
      security:
        - api_key: []
      summary: Returns list of countries who are country_id's neighbour.
      description: Takes country's id (country_id) in path and returns its neighbouring country list.
      parameters:
        - name: country_id
          in: path
          required: True
          schema:
            type: string
            example: 153520e2-8412-4450-9e3e-1cb23d5c1daa
      responses:
        "200":
          description: Returns 200 status code if content found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/country"
        "401":
          $ref: "#/components/responses/401unauthorized_response"

  /api/languages/{language_id}/countries/:
    get:
      security:
        - api_key: []
      summary: Returns list of countries who speaks the languages_id's language
      parameters:
        - name: language_id
          in: path
          required: True
          schema:
            type: string
            example: f54ad185-a501-44e7-a464-64a6e849eed0
      responses:
        "200":
          description: Returns 200 status code if content found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/country"
        "401":
          $ref: "#/components/responses/401unauthorized_response"

components:
  securitySchemes:
    api_key:
      type: apiKey
      description: API key to authorize requests.
      name: Authorization
      in: header

  schemas:
    401unauthorized:
      type: object
      properties:
        detail:
          type: string
          example: Authorization credentials were not provided.

    country:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: c8eb4d82-627d-4582-aca5-fa98b4ab777c
          name:
            type: string
            example: China
          alphacode_2:
            type: string
            example: CN
          capital:
            type: string
            example: Beijing
          population:
            type: integer
            example: 1377422166
          timezone:
            type: string
            example: UTC+08:00
          flag:
            type: string
            example: https://restcountries.eu/data/chn.svg
    countries_schema:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: 8368ac3c-59ea-408e-b9b3-1351ee7ab397
          name:
            type: string
            example: Afghanistan
          alphacode_2:
            type: string
            example: AF
          capital:
            type: string
            example: Kabul
          population:
            type: integer
            example: 27657145
          timezone:
            type: string
            example: UTC+04:30
          flag:
            type: string
            example: https://restcountries.eu/data/afg.svg
  responses:
    "401unauthorized_response":
      description: Returns 401 status code if user is not authorized.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/401unauthorized"

security:
  - api_key: []
