# Generated by Django 3.2.4 on 2021-06-21 18:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(db_column='country_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Country ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('alphacode_2', models.CharField(max_length=256, verbose_name='Alpha Code 2')),
                ('capital', models.CharField(max_length=256, verbose_name='Capital')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('timezone', models.CharField(max_length=256, verbose_name='Timezone')),
                ('flag', models.CharField(max_length=256, verbose_name='Flag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(db_column='language_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Language ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'db_table': 'Language',
            },
        ),
        migrations.CreateModel(
            name='CountryNeighbour',
            fields=[
                ('id', models.UUIDField(db_column='country_neighbour_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Country Neighbour ID')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_of_neighbour_country', to='country.country', verbose_name='Country ID')),
                ('neighbour_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbour_country_of_country', to='country.country', verbose_name='Neighbour Country ID')),
            ],
            options={
                'verbose_name_plural': 'CountryNeighbours',
                'db_table': 'CountryNeighbour',
            },
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.UUIDField(db_column='country_language_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Country Language ID')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_languages', to='country.country', verbose_name='Country ID')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='country.language', verbose_name='Language ID')),
            ],
            options={
                'verbose_name_plural': 'CountryLanguages',
                'db_table': 'CountryLanguage',
            },
        ),
    ]
