# Generated by Django 3.2.4 on 2021-06-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrylanguage',
            options={'verbose_name_plural': 'Country Languages'},
        ),
        migrations.AlterModelOptions(
            name='countryneighbour',
            options={'verbose_name_plural': 'Country Neighbours'},
        ),
    ]
