# Generated by Django 3.2.4 on 2021-06-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_language_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('name', 'flag')},
        ),
    ]
