# Generated by Django 3.2.4 on 2021-06-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20210621_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': '1. Countries'},
        ),
        migrations.AlterModelOptions(
            name='countrylanguage',
            options={'verbose_name_plural': '3. Country Languages'},
        ),
        migrations.AlterModelOptions(
            name='countryneighbour',
            options={'verbose_name_plural': '4. Country Neighbours'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': '2. Languages'},
        ),
    ]
